name: Publish Python Package

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Требуется для OIDC
  contents: read   # Для доступа к коду

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1. Проверяем код из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2. Устанавливаем Python и зависимости
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install build twine

    # Шаг 3. Собираем дистрибутив
    - name: Build the package
      run: python -m build

    # Шаг 4. Публикуем на PyPI через Trusted Publisher
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__  # Используется при Trusted Publisher
        TWINE_PASSWORD: ""         # Пусто, т.к. используем OIDC
        PYPI_REPOSITORY: "pypi"
      run: python -m twine upload dist/*
